/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedSeshesImport } from './routes/_authed/seshes'
import { Route as AuthedLocationsImport } from './routes/_authed/locations'
import { Route as AuthedSeshesIndexImport } from './routes/_authed/seshes/index'
import { Route as AuthedLocationsIndexImport } from './routes/_authed/locations/index'
import { Route as AuthedSeshesSeshIdImport } from './routes/_authed/seshes/$seshId'
import { Route as AuthedProfileSplatImport } from './routes/_authed/profile.$'
import { Route as AuthedLocationsLocationIdImport } from './routes/_authed/locations/$locationId'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedSeshesRoute = AuthedSeshesImport.update({
  id: '/seshes',
  path: '/seshes',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedLocationsRoute = AuthedLocationsImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedSeshesIndexRoute = AuthedSeshesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSeshesRoute,
} as any)

const AuthedLocationsIndexRoute = AuthedLocationsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLocationsRoute,
} as any)

const AuthedSeshesSeshIdRoute = AuthedSeshesSeshIdImport.update({
  id: '/$seshId',
  path: '/$seshId',
  getParentRoute: () => AuthedSeshesRoute,
} as any)

const AuthedProfileSplatRoute = AuthedProfileSplatImport.update({
  id: '/profile/$',
  path: '/profile/$',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedLocationsLocationIdRoute = AuthedLocationsLocationIdImport.update({
  id: '/$locationId',
  path: '/$locationId',
  getParentRoute: () => AuthedLocationsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_authed/locations': {
      id: '/_authed/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthedLocationsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/seshes': {
      id: '/_authed/seshes'
      path: '/seshes'
      fullPath: '/seshes'
      preLoaderRoute: typeof AuthedSeshesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/locations/$locationId': {
      id: '/_authed/locations/$locationId'
      path: '/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AuthedLocationsLocationIdImport
      parentRoute: typeof AuthedLocationsImport
    }
    '/_authed/profile/$': {
      id: '/_authed/profile/$'
      path: '/profile/$'
      fullPath: '/profile/$'
      preLoaderRoute: typeof AuthedProfileSplatImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/seshes/$seshId': {
      id: '/_authed/seshes/$seshId'
      path: '/$seshId'
      fullPath: '/seshes/$seshId'
      preLoaderRoute: typeof AuthedSeshesSeshIdImport
      parentRoute: typeof AuthedSeshesImport
    }
    '/_authed/locations/': {
      id: '/_authed/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthedLocationsIndexImport
      parentRoute: typeof AuthedLocationsImport
    }
    '/_authed/seshes/': {
      id: '/_authed/seshes/'
      path: '/'
      fullPath: '/seshes/'
      preLoaderRoute: typeof AuthedSeshesIndexImport
      parentRoute: typeof AuthedSeshesImport
    }
  }
}

// Create and export the route tree

interface AuthedLocationsRouteChildren {
  AuthedLocationsLocationIdRoute: typeof AuthedLocationsLocationIdRoute
  AuthedLocationsIndexRoute: typeof AuthedLocationsIndexRoute
}

const AuthedLocationsRouteChildren: AuthedLocationsRouteChildren = {
  AuthedLocationsLocationIdRoute: AuthedLocationsLocationIdRoute,
  AuthedLocationsIndexRoute: AuthedLocationsIndexRoute,
}

const AuthedLocationsRouteWithChildren = AuthedLocationsRoute._addFileChildren(
  AuthedLocationsRouteChildren,
)

interface AuthedSeshesRouteChildren {
  AuthedSeshesSeshIdRoute: typeof AuthedSeshesSeshIdRoute
  AuthedSeshesIndexRoute: typeof AuthedSeshesIndexRoute
}

const AuthedSeshesRouteChildren: AuthedSeshesRouteChildren = {
  AuthedSeshesSeshIdRoute: AuthedSeshesSeshIdRoute,
  AuthedSeshesIndexRoute: AuthedSeshesIndexRoute,
}

const AuthedSeshesRouteWithChildren = AuthedSeshesRoute._addFileChildren(
  AuthedSeshesRouteChildren,
)

interface AuthedRouteChildren {
  AuthedLocationsRoute: typeof AuthedLocationsRouteWithChildren
  AuthedSeshesRoute: typeof AuthedSeshesRouteWithChildren
  AuthedProfileSplatRoute: typeof AuthedProfileSplatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLocationsRoute: AuthedLocationsRouteWithChildren,
  AuthedSeshesRoute: AuthedSeshesRouteWithChildren,
  AuthedProfileSplatRoute: AuthedProfileSplatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/locations': typeof AuthedLocationsRouteWithChildren
  '/seshes': typeof AuthedSeshesRouteWithChildren
  '/locations/$locationId': typeof AuthedLocationsLocationIdRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/seshes/$seshId': typeof AuthedSeshesSeshIdRoute
  '/locations/': typeof AuthedLocationsIndexRoute
  '/seshes/': typeof AuthedSeshesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/locations/$locationId': typeof AuthedLocationsLocationIdRoute
  '/profile/$': typeof AuthedProfileSplatRoute
  '/seshes/$seshId': typeof AuthedSeshesSeshIdRoute
  '/locations': typeof AuthedLocationsIndexRoute
  '/seshes': typeof AuthedSeshesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/locations': typeof AuthedLocationsRouteWithChildren
  '/_authed/seshes': typeof AuthedSeshesRouteWithChildren
  '/_authed/locations/$locationId': typeof AuthedLocationsLocationIdRoute
  '/_authed/profile/$': typeof AuthedProfileSplatRoute
  '/_authed/seshes/$seshId': typeof AuthedSeshesSeshIdRoute
  '/_authed/locations/': typeof AuthedLocationsIndexRoute
  '/_authed/seshes/': typeof AuthedSeshesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/locations'
    | '/seshes'
    | '/locations/$locationId'
    | '/profile/$'
    | '/seshes/$seshId'
    | '/locations/'
    | '/seshes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/locations/$locationId'
    | '/profile/$'
    | '/seshes/$seshId'
    | '/locations'
    | '/seshes'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/locations'
    | '/_authed/seshes'
    | '/_authed/locations/$locationId'
    | '/_authed/profile/$'
    | '/_authed/seshes/$seshId'
    | '/_authed/locations/'
    | '/_authed/seshes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/locations",
        "/_authed/seshes",
        "/_authed/profile/$"
      ]
    },
    "/_authed/locations": {
      "filePath": "_authed/locations.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/locations/$locationId",
        "/_authed/locations/"
      ]
    },
    "/_authed/seshes": {
      "filePath": "_authed/seshes.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/seshes/$seshId",
        "/_authed/seshes/"
      ]
    },
    "/_authed/locations/$locationId": {
      "filePath": "_authed/locations/$locationId.tsx",
      "parent": "/_authed/locations"
    },
    "/_authed/profile/$": {
      "filePath": "_authed/profile.$.tsx",
      "parent": "/_authed"
    },
    "/_authed/seshes/$seshId": {
      "filePath": "_authed/seshes/$seshId.tsx",
      "parent": "/_authed/seshes"
    },
    "/_authed/locations/": {
      "filePath": "_authed/locations/index.tsx",
      "parent": "/_authed/locations"
    },
    "/_authed/seshes/": {
      "filePath": "_authed/seshes/index.tsx",
      "parent": "/_authed/seshes"
    }
  }
}
ROUTE_MANIFEST_END */
